$(shell mkdir -p /mnt/disk/jenkins/ci/workspace/chipset_Q_ATLANTA_R_LV_1016/opensource/component_code/out/target/product/kirin980/obj/KERNEL_OBJ/arch/arm64/boot/dts/auto-generate/config/kirin980)
include /mnt/disk/jenkins/ci/workspace/chipset_Q_ATLANTA_R_LV_1016/opensource/component_code/kernel/linux-4.14/arch/arm64/boot/dts/auto-generate/config/kirin980/kirin980_dtb.mk
dtbs: kirin980_dtb
