/*---------------------------------------------------------------------------
 * This file is autogenerated file using huawei LCD parser. Please do not edit it.
 * Update input XML file to add a new entry or update variable in this file
 * Parser location: vendor/huawei/chipset_common/devkit/lcdkit/tools 
 *---------------------------------------------------------------------------*/

#ifndef _LCDKIT_EFFECT__H_
#define _LCDKIT_EFFECT__H_


#include "plat_effect_para.h"

#include "hma_tugl_lg_nt36772a_hma.h"

#include "hma_tugl_jdi_td4336_hma.h"

#include "hma_tugl_sharp_td4336_hma.h"

#include "hma_tugl_lg_nt36772a_hma_v2.h"

#include "hma_tugl_jdi_td4336_hma_v2.h"

#include "hma_tugl_sharp_td4336_hma_v2.h"

#include "hma_tugl_boe_hx83112e_hma.h"

#include "hma_tugl_lg_nt36772a_rt8555.h"

#include "hma_tugl_jdi_td4336_rt8555.h"

#include "hma_tugl_sharp_td4336_rt8555.h"

#include "laya_tugl_boe_r66451_laya.h"

#include "laya_tugl_lg_ea9151_laya.h"

#include "pct_ctc_nt36672a_6p4.h"

#include "pct_boe_td4320_6p4.h"

#include "pct_auo_td4320_6p4.h"

#include "pct_auo_nt36672a_6p4.h"

#include "pct_boe_nt36672a_6p4.h"

#include "pct_lg_td4320_6p4.h"

#include "pct_tm_nt36672a_6p4.h"

#include "pct_v4_ctc_nt36672a_6p4.h"

#include "pct_v4_boe_td4320_6p4.h"

#include "pct_v4_auo_td4320_6p4.h"

#include "pct_v4_auo_nt36672a_6p4.h"

#include "pct_v4_boe_nt36672a_6p4.h"

#include "pct_v4_lg_td4320_6p4.h"

#include "pct_v4_tm_nt36672a_6p4.h"

#include "tahiti_tugl_boe_nt37800f_tah.h"

#include "yal_boe_nt36672a_6p26.h"

#include "yal_ctc_ft8719_6p26.h"

#include "yal_ctc_nt36672a_6p26.h"

#include "yal_lg_td4320_6p26.h"

#include "yal_tm_nt36672a_6p26.h"

#include "yal_tm_td4320_6p26.h"

#include "yal_tm_td4330_6p26.h"

#include "yal_v4_boe_nt36672a_6p26.h"

#include "yal_v4_ctc_ft8719_6p26.h"

#include "yal_v4_ctc_nt36672a_6p26.h"

#include "yal_v4_lg_td4320_6p26.h"

#include "yal_v4_tm_nt36672a_6p26.h"

#include "yal_v4_tm_td4320_6p26.h"

#include "yal_v4_tm_td4330_6p26.h"

/*---------------------------------------------------------------------------*/
/* static panel selection variable                                           */
/*---------------------------------------------------------------------------*/
enum {
HMA_TUGL_SAMSUNG_EA8074_PANEL,
HMA_TUGL_SAMSUNG_V2_EA8074_PANEL,
HMA_TUGL_LG_NT36772A_HMA_PANEL,
HMA_TUGL_JDI_TD4336_HMA_PANEL,
HMA_TUGL_SHARP_TD4336_HMA_PANEL,
HMA_TUGL_LG_NT36772A_HMA_V2_PANEL,
HMA_TUGL_JDI_TD4336_HMA_V2_PANEL,
HMA_TUGL_SHARP_TD4336_HMA_V2_PANEL,
HMA_TUGL_BOE_HX83112E_HMA_PANEL,
HMA_TUGL_LG_NT36772A_RT8555_PANEL,
HMA_TUGL_JDI_TD4336_RT8555_PANEL,
HMA_TUGL_SHARP_TD4336_RT8555_PANEL,
LAYA_TUGL_BOE_R66451_LAYA_PANEL,
LAYA_TUGL_LG_EA9151_LAYA_PANEL,
HMA_TUGL_AUO_OTM1901A_5P2_1080P_VIDEO_DEFAULT_PANEL,
LAYA_TUGL_AUO_OTM1901A_5P2_1080P_VIDEO_DEFAULT_PANEL,
TNY_SAMSUNG_EA8076_PANEL,
TNY_V4_SAMSUNG_EA8076_PANEL,
TNY_AUO_OTM1901A_5P2_1080P_VIDEO_DEFAULT_PANEL,
EVER_SAMSUNG_EA8074_EVER_6P95_PANEL,
EVER_SAMSUNG_EA8074_EVER_PANEL,
EVER_SAMSUNG_EA8074_EVER_VN1_PANEL,
EVER_AUO_OTM1901A_5P2_1080P_VIDEO_DEFAULT_PANEL,
ELLE_TUGL_SAMSUNG_EA8074_ELLE_PANEL,
ELLE_TUGL_SAMSUNG_EA8076_ELLE_PANEL,
ELLE_TUGL_SAMSUNG_EA8076_ELLE_V_PANEL,
ELLE_TUGL_AUO_OTM1901A_5P2_1080P_VIDEO_DEFAULT_PANEL,
PCT_CTC_NT36672A_6P4_PANEL,
PCT_BOE_TD4320_6P4_PANEL,
PCT_AUO_TD4320_6P4_PANEL,
PCT_AUO_NT36672A_6P4_PANEL,
PCT_BOE_NT36672A_6P4_PANEL,
PCT_LG_TD4320_6P4_PANEL,
PCT_TM_NT36672A_6P4_PANEL,
PCT_V4_CTC_NT36672A_6P4_PANEL,
PCT_V4_BOE_TD4320_6P4_PANEL,
PCT_V4_AUO_TD4320_6P4_PANEL,
PCT_V4_AUO_NT36672A_6P4_PANEL,
PCT_V4_BOE_NT36672A_6P4_PANEL,
PCT_V4_LG_TD4320_6P4_PANEL,
PCT_V4_TM_NT36672A_6P4_PANEL,
PCT_AUO_OTM1901A_5P2_1080P_VIDEO_DEFAULT_PANEL,
SCM_BOEDVT2_NT35523_10P7_PANEL,
SCM_INX_NT35523_10P7_PANEL,
SCM_AUO_OTM1901A_5P2_1080P_VIDEO_DEFAULT_PANEL,
VOGUE_TUGL_LG_NT37280_VOGUE_PANEL,
VOGUE_TUGL_BOE_NT37700F_VOGUE_PANEL,
VOGUE_TUGL_LG_NT37280_VOGUE_P_PANEL,
VOGUE_TUGL_BOE_NT37700F_VOGUE_P_PANEL,
VOGUE_TUGL_AUO_OTM1901A_5P2_1080P_VIDEO_DEFAULT_PANEL,
DEFAULT_AUO_OTM1901A_5P2_1080P_VIDEO_DEFAULT_PANEL,
TAHITI_TUGL_BOE_3LANE_NT37700F_PANEL,
TAHITI_TUGL_BOE_NT37800F_TAH_PANEL,
TAHITI_TUGL_AUO_OTM1901A_5P2_1080P_VIDEO_DEFAULT_PANEL,
RSN_TIANMA1_R63319_8P4_1600P_VIDEO_PANEL,
RSN_AUO_OTM1901A_5P2_1080P_VIDEO_DEFAULT_PANEL,
VRD_TIANMA_R63319_8P4_PANEL,
VRD_CSOT_R63319_8P4_PANEL,
VRD_AUO_OTM1901A_5P2_1080P_VIDEO_DEFAULT_PANEL,
YAL_BOE_NT36672A_6P26_PANEL,
YAL_CTC_FT8719_6P26_PANEL,
YAL_CTC_NT36672A_6P26_PANEL,
YAL_LG_TD4320_6P26_PANEL,
YAL_TM_NT36672A_6P26_PANEL,
YAL_TM_TD4320_6P26_PANEL,
YAL_TM_TD4330_6P26_PANEL,
YAL_V4_BOE_NT36672A_6P26_PANEL,
YAL_V4_CTC_FT8719_6P26_PANEL,
YAL_V4_CTC_NT36672A_6P26_PANEL,
YAL_V4_LG_TD4320_6P26_PANEL,
YAL_V4_TM_NT36672A_6P26_PANEL,
YAL_V4_TM_TD4320_6P26_PANEL,
YAL_V4_TM_TD4330_6P26_PANEL,
YAL_AUO_OTM1901A_5P2_1080P_VIDEO_DEFAULT_PANEL,
SEA_SAMSUNG_EA8076_PANEL,
SEA_V3_SAMSUNG_EA8076_PANEL,
SEA_V4_SAMSUNG_EA8076_PANEL,
SEA_AUO_OTM1901A_5P2_1080P_VIDEO_DEFAULT_PANEL,
PANDA_SAMSUNG_EA8074_PANDA_PANEL,
PANDA_AUO_OTM1901A_5P2_1080P_VIDEO_DEFAULT_PANEL,
INVALID_PANEL_ID,
};


/*---------------------------------------------------------------------------*/
/* static panel board mapping variable                                           */
/*---------------------------------------------------------------------------*/
struct lcd_kit_board_map {
    uint8_t lcd_id;
    char *panel_compatible;
    uint32_t product_id;
};

static struct lcd_kit_board_map lcd_kit_map[] = {
    {HMA_TUGL_SAMSUNG_EA8074_PANEL, "samsung_ea8074_6p01_1080plus_cmd", 1000},
    {HMA_TUGL_SAMSUNG_V2_EA8074_PANEL, "samsung_v2_ea8074_6p01_1080plus_cmd", 1000},
    {HMA_TUGL_LG_NT36772A_HMA_PANEL, "lg_nt36772a_hma_6p53_1080plus_cmd", 1001},
    {HMA_TUGL_JDI_TD4336_HMA_PANEL, "jdi_td4336_hma_6p53_1080plus_cmd", 1001},
    {HMA_TUGL_SHARP_TD4336_HMA_PANEL, "sharp_td4336_hma_6p53_1080plus_cmd", 1001},
    {HMA_TUGL_LG_NT36772A_HMA_V2_PANEL, "lg_nt36772a_hma_v2_6p53_1080plus_cmd", 1002},
    {HMA_TUGL_JDI_TD4336_HMA_V2_PANEL, "jdi_td4336_hma_v2_6p53_1080plus_cmd", 1002},
    {HMA_TUGL_SHARP_TD4336_HMA_V2_PANEL, "sharp_td4336_hma_v2_6p53_1080plus_cmd", 1002},
    {HMA_TUGL_BOE_HX83112E_HMA_PANEL, "boe_hx83112e_hma_6p53_1080plus_cmd", 1002},
    {HMA_TUGL_LG_NT36772A_RT8555_PANEL, "lg_nt36772a_hma_v2_6p53_1080plus_cmd", 1003},
    {HMA_TUGL_JDI_TD4336_RT8555_PANEL, "jdi_td4336_hma_v2_6p53_1080plus_cmd", 1003},
    {HMA_TUGL_SHARP_TD4336_RT8555_PANEL, "sharp_td4336_hma_v2_6p53_1080plus_cmd", 1003},
    {LAYA_TUGL_BOE_R66451_LAYA_PANEL, "boe_r66451_laya", 2000},
    {LAYA_TUGL_LG_EA9151_LAYA_PANEL, "lg_ea9151_laya", 2000},
    {HMA_TUGL_AUO_OTM1901A_5P2_1080P_VIDEO_DEFAULT_PANEL, "auo_otm1901a_5p2_1080p_video_default", 0},
    {LAYA_TUGL_AUO_OTM1901A_5P2_1080P_VIDEO_DEFAULT_PANEL, "auo_otm1901a_5p2_1080p_video_default", 0},
    {TNY_SAMSUNG_EA8076_PANEL, "samsung_ea8076", 3000},
    {TNY_V4_SAMSUNG_EA8076_PANEL, "samsung_ea8076", 3001},
    {TNY_AUO_OTM1901A_5P2_1080P_VIDEO_DEFAULT_PANEL, "auo_otm1901a_5p2_1080p_video_default", 0},
    {EVER_SAMSUNG_EA8074_EVER_6P95_PANEL, "samsung_ea8074_ever_6p95_1080plus_cmd", 4000},
    {EVER_SAMSUNG_EA8074_EVER_PANEL, "samsung_ea8074_ever_7p21_1080plus_cmd", 4000},
    {EVER_SAMSUNG_EA8074_EVER_VN1_PANEL, "samsung_ea8074_ever_vn1_7p21_1080plus_cmd", 4001},
    {EVER_AUO_OTM1901A_5P2_1080P_VIDEO_DEFAULT_PANEL, "auo_otm1901a_5p2_1080p_video_default", 0},
    {ELLE_TUGL_SAMSUNG_EA8074_ELLE_PANEL, "samsung_ea8074_elle_6p10_1080plus_cmd", 5000},
    {ELLE_TUGL_SAMSUNG_EA8076_ELLE_PANEL, "samsung_ea8076_elle_6p11_1080plus_cmd", 5000},
    {ELLE_TUGL_SAMSUNG_EA8076_ELLE_V_PANEL, "samsung_ea8076_elle_v2_6p11_1080plus_cmd", 5001},
    {ELLE_TUGL_AUO_OTM1901A_5P2_1080P_VIDEO_DEFAULT_PANEL, "auo_otm1901a_5p2_1080p_video_default", 0},
    {PCT_CTC_NT36672A_6P4_PANEL, "ctc_nt36672a_6p4", 6000},
    {PCT_BOE_TD4320_6P4_PANEL, "boe_td4320_6p4", 6000},
    {PCT_AUO_TD4320_6P4_PANEL, "auo_td4320_6p4", 6000},
    {PCT_AUO_NT36672A_6P4_PANEL, "auo_nt36672a_6p4", 6000},
    {PCT_BOE_NT36672A_6P4_PANEL, "boe_nt36672a_6p4", 6000},
    {PCT_LG_TD4320_6P4_PANEL, "lg_td4320_6p4", 6000},
    {PCT_TM_NT36672A_6P4_PANEL, "tm_nt36672a_6p4", 6000},
    {PCT_V4_CTC_NT36672A_6P4_PANEL, "ctc_nt36672a_6p4", 6001},
    {PCT_V4_BOE_TD4320_6P4_PANEL, "boe_td4320_6p4", 6001},
    {PCT_V4_AUO_TD4320_6P4_PANEL, "auo_td4320_6p4", 6001},
    {PCT_V4_AUO_NT36672A_6P4_PANEL, "auo_nt36672a_6p4", 6001},
    {PCT_V4_BOE_NT36672A_6P4_PANEL, "boe_nt36672a_6p4", 6001},
    {PCT_V4_LG_TD4320_6P4_PANEL, "lg_td4320_6p4", 6001},
    {PCT_V4_TM_NT36672A_6P4_PANEL, "tm_nt36672a_6p4", 6001},
    {PCT_AUO_OTM1901A_5P2_1080P_VIDEO_DEFAULT_PANEL, "auo_otm1901a_5p2_1080p_video_default", 0},
    {SCM_BOEDVT2_NT35523_10P7_PANEL, "boedvt2-nt35523-10p7-1600p-video", 7001},
    {SCM_INX_NT35523_10P7_PANEL, "inx-nt35523-10p7-1600p-video", 7001},
    {SCM_AUO_OTM1901A_5P2_1080P_VIDEO_DEFAULT_PANEL, "auo_otm1901a_5p2_1080p_video_default", 0},
    {VOGUE_TUGL_LG_NT37280_VOGUE_PANEL, "lg_nt37280_vogue_6p47_1080plus_cmd", 8000},
    {VOGUE_TUGL_BOE_NT37700F_VOGUE_PANEL, "boe_nt37700f_vogue_6p47_1080plus_cmd", 8000},
    {VOGUE_TUGL_LG_NT37280_VOGUE_P_PANEL, "lg_nt37280_vogue_p_6p47_1080plus_cmd", 8001},
    {VOGUE_TUGL_BOE_NT37700F_VOGUE_P_PANEL, "boe_nt37700f_vogue_p_6p47_1080plus_cmd", 8001},
    {VOGUE_TUGL_AUO_OTM1901A_5P2_1080P_VIDEO_DEFAULT_PANEL, "auo_otm1901a_5p2_1080p_video_default", 0},
    {DEFAULT_AUO_OTM1901A_5P2_1080P_VIDEO_DEFAULT_PANEL, "auo_otm1901a_5p2_1080p_video_default", 0},
    {TAHITI_TUGL_BOE_3LANE_NT37700F_PANEL, "boe_3lane_nt37700f_8p03_2mux_cmd", 9000},
    {TAHITI_TUGL_BOE_NT37800F_TAH_PANEL, "boe-nt37800f-tah-8p03-3lane-2mux-cmd", 9001},
    {TAHITI_TUGL_AUO_OTM1901A_5P2_1080P_VIDEO_DEFAULT_PANEL, "auo_otm1901a_5p2_1080p_video_default", 0},
    {RSN_TIANMA1_R63319_8P4_1600P_VIDEO_PANEL, "tianma1_r63319_8p4_1600p_video", 10000},
    {RSN_AUO_OTM1901A_5P2_1080P_VIDEO_DEFAULT_PANEL, "auo_otm1901a_5p2_1080p_video_default", 0},
    {VRD_TIANMA_R63319_8P4_PANEL, "tianma_r63319_8p4_1600p_video", 11000},
    {VRD_CSOT_R63319_8P4_PANEL, "csot_r63319_8p4", 11000},
    {VRD_AUO_OTM1901A_5P2_1080P_VIDEO_DEFAULT_PANEL, "auo_otm1901a_5p2_1080p_video_default", 0},
    {YAL_BOE_NT36672A_6P26_PANEL, "boe_nt36672a_6p26", 13000},
    {YAL_CTC_FT8719_6P26_PANEL, "ctc_ft8719_6p26", 13000},
    {YAL_CTC_NT36672A_6P26_PANEL, "ctc_nt36672a_6p26", 13000},
    {YAL_LG_TD4320_6P26_PANEL, "lg_td4320_6p26", 13000},
    {YAL_TM_NT36672A_6P26_PANEL, "tm_nt36672a_6p26", 13000},
    {YAL_TM_TD4320_6P26_PANEL, "tm_td4320_6p26", 13000},
    {YAL_TM_TD4330_6P26_PANEL, "tm_td4330_6p26", 13000},
    {YAL_V4_BOE_NT36672A_6P26_PANEL, "boe_nt36672a_6p26", 13001},
    {YAL_V4_CTC_FT8719_6P26_PANEL, "ctc_ft8719_6p26", 13001},
    {YAL_V4_CTC_NT36672A_6P26_PANEL, "ctc_nt36672a_6p26", 13001},
    {YAL_V4_LG_TD4320_6P26_PANEL, "lg_td4320_6p26", 13001},
    {YAL_V4_TM_NT36672A_6P26_PANEL, "tm_nt36672a_6p26", 13001},
    {YAL_V4_TM_TD4320_6P26_PANEL, "tm_td4320_6p26", 13001},
    {YAL_V4_TM_TD4330_6P26_PANEL, "tm_td4330_6p26", 13001},
    {YAL_AUO_OTM1901A_5P2_1080P_VIDEO_DEFAULT_PANEL, "auo_otm1901a_5p2_1080p_video_default", 0},
    {SEA_SAMSUNG_EA8076_PANEL, "samsung_ea8076", 14000},
    {SEA_V3_SAMSUNG_EA8076_PANEL, "samsung_ea8076", 14001},
    {SEA_V4_SAMSUNG_EA8076_PANEL, "samsung_ea8076", 14002},
    {SEA_AUO_OTM1901A_5P2_1080P_VIDEO_DEFAULT_PANEL, "auo_otm1901a_5p2_1080p_video_default", 0},
    {PANDA_SAMSUNG_EA8074_PANDA_PANEL, "samsung_ea8074_panda_7p21_cmd", 16000},
    {PANDA_AUO_OTM1901A_5P2_1080P_VIDEO_DEFAULT_PANEL, "auo_otm1901a_5p2_1080p_video_default", 0},
};

static void lcd_kit_effect_get_data(uint8_t panel_id, struct hisi_panel_info* pinfo)
{
    if (pinfo->gamma_support == 1)
    {
        pinfo->gamma_lut_table_R = plat_gamma_lut_table_R;
        pinfo->gamma_lut_table_G = plat_gamma_lut_table_G;
        pinfo->gamma_lut_table_B = plat_gamma_lut_table_B;
        pinfo->gamma_lut_table_len = ARRAY_SIZE(plat_gamma_lut_table_R);
        pinfo->igm_lut_table_R = plat_igm_lut_table_R;
        pinfo->igm_lut_table_G = plat_igm_lut_table_G;
        pinfo->igm_lut_table_B = plat_igm_lut_table_B;
        pinfo->igm_lut_table_len = ARRAY_SIZE(plat_igm_lut_table_R);
        pinfo->gmp_lut_table_low32bit = &plat_gmp_lut_table_low32bit[0][0][0];
        pinfo->gmp_lut_table_high4bit = &plat_gmp_lut_table_high4bit[0][0][0];
        pinfo->gmp_lut_table_len = ARRAY_3_SIZE(plat_gmp_lut_table_low32bit);
        pinfo->xcc_table = plat_xcc_table;
        pinfo->xcc_table_len = ARRAY_SIZE(plat_xcc_table);
    }
    switch (panel_id) {
    case HMA_TUGL_LG_NT36772A_HMA_PANEL:
        if (pinfo->gamma_support == 1)
        {
            pinfo->gamma_lut_table_R = hma_tugl_lg_nt36772a_hma_gamma_lut_table_R;
            pinfo->gamma_lut_table_G = hma_tugl_lg_nt36772a_hma_gamma_lut_table_G;
            pinfo->gamma_lut_table_B = hma_tugl_lg_nt36772a_hma_gamma_lut_table_B;
            pinfo->gamma_lut_table_len = ARRAY_SIZE(hma_tugl_lg_nt36772a_hma_gamma_lut_table_R);
            pinfo->igm_lut_table_R = hma_tugl_lg_nt36772a_hma_igm_lut_table_R;
            pinfo->igm_lut_table_G = hma_tugl_lg_nt36772a_hma_igm_lut_table_G;
            pinfo->igm_lut_table_B = hma_tugl_lg_nt36772a_hma_igm_lut_table_B;
            pinfo->igm_lut_table_len = ARRAY_SIZE(hma_tugl_lg_nt36772a_hma_igm_lut_table_R);
            pinfo->gmp_lut_table_low32bit = &hma_tugl_lg_nt36772a_hma_gmp_lut_table_low32bit[0][0][0];
            pinfo->gmp_lut_table_high4bit = &hma_tugl_lg_nt36772a_hma_gmp_lut_table_high4bit[0][0][0];
            pinfo->gmp_lut_table_len = ARRAY_3_SIZE(hma_tugl_lg_nt36772a_hma_gmp_lut_table_low32bit);
            pinfo->xcc_table = hma_tugl_lg_nt36772a_hma_xcc_table;
            pinfo->xcc_table_len = ARRAY_SIZE(hma_tugl_lg_nt36772a_hma_xcc_table);
        }
        break;
    case HMA_TUGL_JDI_TD4336_HMA_PANEL:
        if (pinfo->gamma_support == 1)
        {
            pinfo->gamma_lut_table_R = hma_tugl_jdi_td4336_hma_gamma_lut_table_R;
            pinfo->gamma_lut_table_G = hma_tugl_jdi_td4336_hma_gamma_lut_table_G;
            pinfo->gamma_lut_table_B = hma_tugl_jdi_td4336_hma_gamma_lut_table_B;
            pinfo->gamma_lut_table_len = ARRAY_SIZE(hma_tugl_jdi_td4336_hma_gamma_lut_table_R);
            pinfo->igm_lut_table_R = hma_tugl_jdi_td4336_hma_igm_lut_table_R;
            pinfo->igm_lut_table_G = hma_tugl_jdi_td4336_hma_igm_lut_table_G;
            pinfo->igm_lut_table_B = hma_tugl_jdi_td4336_hma_igm_lut_table_B;
            pinfo->igm_lut_table_len = ARRAY_SIZE(hma_tugl_jdi_td4336_hma_igm_lut_table_R);
            pinfo->gmp_lut_table_low32bit = &hma_tugl_jdi_td4336_hma_gmp_lut_table_low32bit[0][0][0];
            pinfo->gmp_lut_table_high4bit = &hma_tugl_jdi_td4336_hma_gmp_lut_table_high4bit[0][0][0];
            pinfo->gmp_lut_table_len = ARRAY_3_SIZE(hma_tugl_jdi_td4336_hma_gmp_lut_table_low32bit);
            pinfo->xcc_table = hma_tugl_jdi_td4336_hma_xcc_table;
            pinfo->xcc_table_len = ARRAY_SIZE(hma_tugl_jdi_td4336_hma_xcc_table);
        }
        break;
    case HMA_TUGL_SHARP_TD4336_HMA_PANEL:
        if (pinfo->gamma_support == 1)
        {
            pinfo->gamma_lut_table_R = hma_tugl_sharp_td4336_hma_gamma_lut_table_R;
            pinfo->gamma_lut_table_G = hma_tugl_sharp_td4336_hma_gamma_lut_table_G;
            pinfo->gamma_lut_table_B = hma_tugl_sharp_td4336_hma_gamma_lut_table_B;
            pinfo->gamma_lut_table_len = ARRAY_SIZE(hma_tugl_sharp_td4336_hma_gamma_lut_table_R);
            pinfo->igm_lut_table_R = hma_tugl_sharp_td4336_hma_igm_lut_table_R;
            pinfo->igm_lut_table_G = hma_tugl_sharp_td4336_hma_igm_lut_table_G;
            pinfo->igm_lut_table_B = hma_tugl_sharp_td4336_hma_igm_lut_table_B;
            pinfo->igm_lut_table_len = ARRAY_SIZE(hma_tugl_sharp_td4336_hma_igm_lut_table_R);
            pinfo->gmp_lut_table_low32bit = &hma_tugl_sharp_td4336_hma_gmp_lut_table_low32bit[0][0][0];
            pinfo->gmp_lut_table_high4bit = &hma_tugl_sharp_td4336_hma_gmp_lut_table_high4bit[0][0][0];
            pinfo->gmp_lut_table_len = ARRAY_3_SIZE(hma_tugl_sharp_td4336_hma_gmp_lut_table_low32bit);
            pinfo->xcc_table = hma_tugl_sharp_td4336_hma_xcc_table;
            pinfo->xcc_table_len = ARRAY_SIZE(hma_tugl_sharp_td4336_hma_xcc_table);
        }
        break;
    case HMA_TUGL_LG_NT36772A_HMA_V2_PANEL:
        if (pinfo->gamma_support == 1)
        {
            pinfo->gamma_lut_table_R = hma_tugl_lg_nt36772a_hma_v2_gamma_lut_table_R;
            pinfo->gamma_lut_table_G = hma_tugl_lg_nt36772a_hma_v2_gamma_lut_table_G;
            pinfo->gamma_lut_table_B = hma_tugl_lg_nt36772a_hma_v2_gamma_lut_table_B;
            pinfo->gamma_lut_table_len = ARRAY_SIZE(hma_tugl_lg_nt36772a_hma_v2_gamma_lut_table_R);
            pinfo->igm_lut_table_R = hma_tugl_lg_nt36772a_hma_v2_igm_lut_table_R;
            pinfo->igm_lut_table_G = hma_tugl_lg_nt36772a_hma_v2_igm_lut_table_G;
            pinfo->igm_lut_table_B = hma_tugl_lg_nt36772a_hma_v2_igm_lut_table_B;
            pinfo->igm_lut_table_len = ARRAY_SIZE(hma_tugl_lg_nt36772a_hma_v2_igm_lut_table_R);
            pinfo->gmp_lut_table_low32bit = &hma_tugl_lg_nt36772a_hma_v2_gmp_lut_table_low32bit[0][0][0];
            pinfo->gmp_lut_table_high4bit = &hma_tugl_lg_nt36772a_hma_v2_gmp_lut_table_high4bit[0][0][0];
            pinfo->gmp_lut_table_len = ARRAY_3_SIZE(hma_tugl_lg_nt36772a_hma_v2_gmp_lut_table_low32bit);
            pinfo->xcc_table = hma_tugl_lg_nt36772a_hma_v2_xcc_table;
            pinfo->xcc_table_len = ARRAY_SIZE(hma_tugl_lg_nt36772a_hma_v2_xcc_table);
        }
        break;
    case HMA_TUGL_JDI_TD4336_HMA_V2_PANEL:
        if (pinfo->gamma_support == 1)
        {
            pinfo->gamma_lut_table_R = hma_tugl_jdi_td4336_hma_v2_gamma_lut_table_R;
            pinfo->gamma_lut_table_G = hma_tugl_jdi_td4336_hma_v2_gamma_lut_table_G;
            pinfo->gamma_lut_table_B = hma_tugl_jdi_td4336_hma_v2_gamma_lut_table_B;
            pinfo->gamma_lut_table_len = ARRAY_SIZE(hma_tugl_jdi_td4336_hma_v2_gamma_lut_table_R);
            pinfo->igm_lut_table_R = hma_tugl_jdi_td4336_hma_v2_igm_lut_table_R;
            pinfo->igm_lut_table_G = hma_tugl_jdi_td4336_hma_v2_igm_lut_table_G;
            pinfo->igm_lut_table_B = hma_tugl_jdi_td4336_hma_v2_igm_lut_table_B;
            pinfo->igm_lut_table_len = ARRAY_SIZE(hma_tugl_jdi_td4336_hma_v2_igm_lut_table_R);
            pinfo->gmp_lut_table_low32bit = &hma_tugl_jdi_td4336_hma_v2_gmp_lut_table_low32bit[0][0][0];
            pinfo->gmp_lut_table_high4bit = &hma_tugl_jdi_td4336_hma_v2_gmp_lut_table_high4bit[0][0][0];
            pinfo->gmp_lut_table_len = ARRAY_3_SIZE(hma_tugl_jdi_td4336_hma_v2_gmp_lut_table_low32bit);
            pinfo->xcc_table = hma_tugl_jdi_td4336_hma_v2_xcc_table;
            pinfo->xcc_table_len = ARRAY_SIZE(hma_tugl_jdi_td4336_hma_v2_xcc_table);
        }
        break;
    case HMA_TUGL_SHARP_TD4336_HMA_V2_PANEL:
        if (pinfo->gamma_support == 1)
        {
            pinfo->gamma_lut_table_R = hma_tugl_sharp_td4336_hma_v2_gamma_lut_table_R;
            pinfo->gamma_lut_table_G = hma_tugl_sharp_td4336_hma_v2_gamma_lut_table_G;
            pinfo->gamma_lut_table_B = hma_tugl_sharp_td4336_hma_v2_gamma_lut_table_B;
            pinfo->gamma_lut_table_len = ARRAY_SIZE(hma_tugl_sharp_td4336_hma_v2_gamma_lut_table_R);
            pinfo->igm_lut_table_R = hma_tugl_sharp_td4336_hma_v2_igm_lut_table_R;
            pinfo->igm_lut_table_G = hma_tugl_sharp_td4336_hma_v2_igm_lut_table_G;
            pinfo->igm_lut_table_B = hma_tugl_sharp_td4336_hma_v2_igm_lut_table_B;
            pinfo->igm_lut_table_len = ARRAY_SIZE(hma_tugl_sharp_td4336_hma_v2_igm_lut_table_R);
            pinfo->gmp_lut_table_low32bit = &hma_tugl_sharp_td4336_hma_v2_gmp_lut_table_low32bit[0][0][0];
            pinfo->gmp_lut_table_high4bit = &hma_tugl_sharp_td4336_hma_v2_gmp_lut_table_high4bit[0][0][0];
            pinfo->gmp_lut_table_len = ARRAY_3_SIZE(hma_tugl_sharp_td4336_hma_v2_gmp_lut_table_low32bit);
            pinfo->xcc_table = hma_tugl_sharp_td4336_hma_v2_xcc_table;
            pinfo->xcc_table_len = ARRAY_SIZE(hma_tugl_sharp_td4336_hma_v2_xcc_table);
        }
        break;
    case HMA_TUGL_BOE_HX83112E_HMA_PANEL:
        if (pinfo->gamma_support == 1)
        {
            pinfo->gamma_lut_table_R = hma_tugl_boe_hx83112e_hma_gamma_lut_table_R;
            pinfo->gamma_lut_table_G = hma_tugl_boe_hx83112e_hma_gamma_lut_table_G;
            pinfo->gamma_lut_table_B = hma_tugl_boe_hx83112e_hma_gamma_lut_table_B;
            pinfo->gamma_lut_table_len = ARRAY_SIZE(hma_tugl_boe_hx83112e_hma_gamma_lut_table_R);
            pinfo->igm_lut_table_R = hma_tugl_boe_hx83112e_hma_igm_lut_table_R;
            pinfo->igm_lut_table_G = hma_tugl_boe_hx83112e_hma_igm_lut_table_G;
            pinfo->igm_lut_table_B = hma_tugl_boe_hx83112e_hma_igm_lut_table_B;
            pinfo->igm_lut_table_len = ARRAY_SIZE(hma_tugl_boe_hx83112e_hma_igm_lut_table_R);
            pinfo->gmp_lut_table_low32bit = &hma_tugl_boe_hx83112e_hma_gmp_lut_table_low32bit[0][0][0];
            pinfo->gmp_lut_table_high4bit = &hma_tugl_boe_hx83112e_hma_gmp_lut_table_high4bit[0][0][0];
            pinfo->gmp_lut_table_len = ARRAY_3_SIZE(hma_tugl_boe_hx83112e_hma_gmp_lut_table_low32bit);
            pinfo->xcc_table = hma_tugl_boe_hx83112e_hma_xcc_table;
            pinfo->xcc_table_len = ARRAY_SIZE(hma_tugl_boe_hx83112e_hma_xcc_table);
        }
        break;
    case HMA_TUGL_LG_NT36772A_RT8555_PANEL:
        if (pinfo->gamma_support == 1)
        {
            pinfo->gamma_lut_table_R = hma_tugl_lg_nt36772a_rt8555_gamma_lut_table_R;
            pinfo->gamma_lut_table_G = hma_tugl_lg_nt36772a_rt8555_gamma_lut_table_G;
            pinfo->gamma_lut_table_B = hma_tugl_lg_nt36772a_rt8555_gamma_lut_table_B;
            pinfo->gamma_lut_table_len = ARRAY_SIZE(hma_tugl_lg_nt36772a_rt8555_gamma_lut_table_R);
            pinfo->igm_lut_table_R = hma_tugl_lg_nt36772a_rt8555_igm_lut_table_R;
            pinfo->igm_lut_table_G = hma_tugl_lg_nt36772a_rt8555_igm_lut_table_G;
            pinfo->igm_lut_table_B = hma_tugl_lg_nt36772a_rt8555_igm_lut_table_B;
            pinfo->igm_lut_table_len = ARRAY_SIZE(hma_tugl_lg_nt36772a_rt8555_igm_lut_table_R);
            pinfo->gmp_lut_table_low32bit = &hma_tugl_lg_nt36772a_rt8555_gmp_lut_table_low32bit[0][0][0];
            pinfo->gmp_lut_table_high4bit = &hma_tugl_lg_nt36772a_rt8555_gmp_lut_table_high4bit[0][0][0];
            pinfo->gmp_lut_table_len = ARRAY_3_SIZE(hma_tugl_lg_nt36772a_rt8555_gmp_lut_table_low32bit);
            pinfo->xcc_table = hma_tugl_lg_nt36772a_rt8555_xcc_table;
            pinfo->xcc_table_len = ARRAY_SIZE(hma_tugl_lg_nt36772a_rt8555_xcc_table);
        }
        break;
    case HMA_TUGL_JDI_TD4336_RT8555_PANEL:
        if (pinfo->gamma_support == 1)
        {
            pinfo->gamma_lut_table_R = hma_tugl_jdi_td4336_rt8555_gamma_lut_table_R;
            pinfo->gamma_lut_table_G = hma_tugl_jdi_td4336_rt8555_gamma_lut_table_G;
            pinfo->gamma_lut_table_B = hma_tugl_jdi_td4336_rt8555_gamma_lut_table_B;
            pinfo->gamma_lut_table_len = ARRAY_SIZE(hma_tugl_jdi_td4336_rt8555_gamma_lut_table_R);
            pinfo->igm_lut_table_R = hma_tugl_jdi_td4336_rt8555_igm_lut_table_R;
            pinfo->igm_lut_table_G = hma_tugl_jdi_td4336_rt8555_igm_lut_table_G;
            pinfo->igm_lut_table_B = hma_tugl_jdi_td4336_rt8555_igm_lut_table_B;
            pinfo->igm_lut_table_len = ARRAY_SIZE(hma_tugl_jdi_td4336_rt8555_igm_lut_table_R);
            pinfo->gmp_lut_table_low32bit = &hma_tugl_jdi_td4336_rt8555_gmp_lut_table_low32bit[0][0][0];
            pinfo->gmp_lut_table_high4bit = &hma_tugl_jdi_td4336_rt8555_gmp_lut_table_high4bit[0][0][0];
            pinfo->gmp_lut_table_len = ARRAY_3_SIZE(hma_tugl_jdi_td4336_rt8555_gmp_lut_table_low32bit);
            pinfo->xcc_table = hma_tugl_jdi_td4336_rt8555_xcc_table;
            pinfo->xcc_table_len = ARRAY_SIZE(hma_tugl_jdi_td4336_rt8555_xcc_table);
        }
        break;
    case HMA_TUGL_SHARP_TD4336_RT8555_PANEL:
        if (pinfo->gamma_support == 1)
        {
            pinfo->gamma_lut_table_R = hma_tugl_sharp_td4336_rt8555_gamma_lut_table_R;
            pinfo->gamma_lut_table_G = hma_tugl_sharp_td4336_rt8555_gamma_lut_table_G;
            pinfo->gamma_lut_table_B = hma_tugl_sharp_td4336_rt8555_gamma_lut_table_B;
            pinfo->gamma_lut_table_len = ARRAY_SIZE(hma_tugl_sharp_td4336_rt8555_gamma_lut_table_R);
            pinfo->igm_lut_table_R = hma_tugl_sharp_td4336_rt8555_igm_lut_table_R;
            pinfo->igm_lut_table_G = hma_tugl_sharp_td4336_rt8555_igm_lut_table_G;
            pinfo->igm_lut_table_B = hma_tugl_sharp_td4336_rt8555_igm_lut_table_B;
            pinfo->igm_lut_table_len = ARRAY_SIZE(hma_tugl_sharp_td4336_rt8555_igm_lut_table_R);
            pinfo->gmp_lut_table_low32bit = &hma_tugl_sharp_td4336_rt8555_gmp_lut_table_low32bit[0][0][0];
            pinfo->gmp_lut_table_high4bit = &hma_tugl_sharp_td4336_rt8555_gmp_lut_table_high4bit[0][0][0];
            pinfo->gmp_lut_table_len = ARRAY_3_SIZE(hma_tugl_sharp_td4336_rt8555_gmp_lut_table_low32bit);
            pinfo->xcc_table = hma_tugl_sharp_td4336_rt8555_xcc_table;
            pinfo->xcc_table_len = ARRAY_SIZE(hma_tugl_sharp_td4336_rt8555_xcc_table);
        }
        break;
    case LAYA_TUGL_BOE_R66451_LAYA_PANEL:
        if (pinfo->gamma_support == 1)
        {
            pinfo->gamma_lut_table_R = laya_tugl_boe_r66451_laya_gamma_lut_table_R;
            pinfo->gamma_lut_table_G = laya_tugl_boe_r66451_laya_gamma_lut_table_G;
            pinfo->gamma_lut_table_B = laya_tugl_boe_r66451_laya_gamma_lut_table_B;
            pinfo->gamma_lut_table_len = ARRAY_SIZE(laya_tugl_boe_r66451_laya_gamma_lut_table_R);
            pinfo->igm_lut_table_R = laya_tugl_boe_r66451_laya_igm_lut_table_R;
            pinfo->igm_lut_table_G = laya_tugl_boe_r66451_laya_igm_lut_table_G;
            pinfo->igm_lut_table_B = laya_tugl_boe_r66451_laya_igm_lut_table_B;
            pinfo->igm_lut_table_len = ARRAY_SIZE(laya_tugl_boe_r66451_laya_igm_lut_table_R);
            pinfo->gmp_lut_table_low32bit = &laya_tugl_boe_r66451_laya_gmp_lut_table_low32bit[0][0][0];
            pinfo->gmp_lut_table_high4bit = &laya_tugl_boe_r66451_laya_gmp_lut_table_high4bit[0][0][0];
            pinfo->gmp_lut_table_len = ARRAY_3_SIZE(laya_tugl_boe_r66451_laya_gmp_lut_table_low32bit);
            pinfo->xcc_table = laya_tugl_boe_r66451_laya_xcc_table;
            pinfo->xcc_table_len = ARRAY_SIZE(laya_tugl_boe_r66451_laya_xcc_table);
        }
        break;
    case LAYA_TUGL_LG_EA9151_LAYA_PANEL:
        if (pinfo->gamma_support == 1)
        {
            pinfo->gamma_lut_table_R = laya_tugl_lg_ea9151_laya_gamma_lut_table_R;
            pinfo->gamma_lut_table_G = laya_tugl_lg_ea9151_laya_gamma_lut_table_G;
            pinfo->gamma_lut_table_B = laya_tugl_lg_ea9151_laya_gamma_lut_table_B;
            pinfo->gamma_lut_table_len = ARRAY_SIZE(laya_tugl_lg_ea9151_laya_gamma_lut_table_R);
            pinfo->igm_lut_table_R = laya_tugl_lg_ea9151_laya_igm_lut_table_R;
            pinfo->igm_lut_table_G = laya_tugl_lg_ea9151_laya_igm_lut_table_G;
            pinfo->igm_lut_table_B = laya_tugl_lg_ea9151_laya_igm_lut_table_B;
            pinfo->igm_lut_table_len = ARRAY_SIZE(laya_tugl_lg_ea9151_laya_igm_lut_table_R);
            pinfo->gmp_lut_table_low32bit = &laya_tugl_lg_ea9151_laya_gmp_lut_table_low32bit[0][0][0];
            pinfo->gmp_lut_table_high4bit = &laya_tugl_lg_ea9151_laya_gmp_lut_table_high4bit[0][0][0];
            pinfo->gmp_lut_table_len = ARRAY_3_SIZE(laya_tugl_lg_ea9151_laya_gmp_lut_table_low32bit);
            pinfo->xcc_table = laya_tugl_lg_ea9151_laya_xcc_table;
            pinfo->xcc_table_len = ARRAY_SIZE(laya_tugl_lg_ea9151_laya_xcc_table);
        }
        break;
    case PCT_CTC_NT36672A_6P4_PANEL:
        if (pinfo->gamma_support == 1)
        {
            pinfo->gamma_lut_table_R = pct_ctc_nt36672a_6p4_gamma_lut_table_R;
            pinfo->gamma_lut_table_G = pct_ctc_nt36672a_6p4_gamma_lut_table_G;
            pinfo->gamma_lut_table_B = pct_ctc_nt36672a_6p4_gamma_lut_table_B;
            pinfo->gamma_lut_table_len = ARRAY_SIZE(pct_ctc_nt36672a_6p4_gamma_lut_table_R);
            pinfo->igm_lut_table_R = pct_ctc_nt36672a_6p4_igm_lut_table_R;
            pinfo->igm_lut_table_G = pct_ctc_nt36672a_6p4_igm_lut_table_G;
            pinfo->igm_lut_table_B = pct_ctc_nt36672a_6p4_igm_lut_table_B;
            pinfo->igm_lut_table_len = ARRAY_SIZE(pct_ctc_nt36672a_6p4_igm_lut_table_R);
            pinfo->gmp_lut_table_low32bit = &pct_ctc_nt36672a_6p4_gmp_lut_table_low32bit[0][0][0];
            pinfo->gmp_lut_table_high4bit = &pct_ctc_nt36672a_6p4_gmp_lut_table_high4bit[0][0][0];
            pinfo->gmp_lut_table_len = ARRAY_3_SIZE(pct_ctc_nt36672a_6p4_gmp_lut_table_low32bit);
            pinfo->xcc_table = pct_ctc_nt36672a_6p4_xcc_table;
            pinfo->xcc_table_len = ARRAY_SIZE(pct_ctc_nt36672a_6p4_xcc_table);
        }
        break;
    case PCT_BOE_TD4320_6P4_PANEL:
        if (pinfo->gamma_support == 1)
        {
            pinfo->gamma_lut_table_R = pct_boe_td4320_6p4_gamma_lut_table_R;
            pinfo->gamma_lut_table_G = pct_boe_td4320_6p4_gamma_lut_table_G;
            pinfo->gamma_lut_table_B = pct_boe_td4320_6p4_gamma_lut_table_B;
            pinfo->gamma_lut_table_len = ARRAY_SIZE(pct_boe_td4320_6p4_gamma_lut_table_R);
            pinfo->igm_lut_table_R = pct_boe_td4320_6p4_igm_lut_table_R;
            pinfo->igm_lut_table_G = pct_boe_td4320_6p4_igm_lut_table_G;
            pinfo->igm_lut_table_B = pct_boe_td4320_6p4_igm_lut_table_B;
            pinfo->igm_lut_table_len = ARRAY_SIZE(pct_boe_td4320_6p4_igm_lut_table_R);
            pinfo->gmp_lut_table_low32bit = &pct_boe_td4320_6p4_gmp_lut_table_low32bit[0][0][0];
            pinfo->gmp_lut_table_high4bit = &pct_boe_td4320_6p4_gmp_lut_table_high4bit[0][0][0];
            pinfo->gmp_lut_table_len = ARRAY_3_SIZE(pct_boe_td4320_6p4_gmp_lut_table_low32bit);
            pinfo->xcc_table = pct_boe_td4320_6p4_xcc_table;
            pinfo->xcc_table_len = ARRAY_SIZE(pct_boe_td4320_6p4_xcc_table);
        }
        break;
    case PCT_AUO_TD4320_6P4_PANEL:
        if (pinfo->gamma_support == 1)
        {
            pinfo->gamma_lut_table_R = pct_auo_td4320_6p4_gamma_lut_table_R;
            pinfo->gamma_lut_table_G = pct_auo_td4320_6p4_gamma_lut_table_G;
            pinfo->gamma_lut_table_B = pct_auo_td4320_6p4_gamma_lut_table_B;
            pinfo->gamma_lut_table_len = ARRAY_SIZE(pct_auo_td4320_6p4_gamma_lut_table_R);
            pinfo->igm_lut_table_R = pct_auo_td4320_6p4_igm_lut_table_R;
            pinfo->igm_lut_table_G = pct_auo_td4320_6p4_igm_lut_table_G;
            pinfo->igm_lut_table_B = pct_auo_td4320_6p4_igm_lut_table_B;
            pinfo->igm_lut_table_len = ARRAY_SIZE(pct_auo_td4320_6p4_igm_lut_table_R);
            pinfo->gmp_lut_table_low32bit = &pct_auo_td4320_6p4_gmp_lut_table_low32bit[0][0][0];
            pinfo->gmp_lut_table_high4bit = &pct_auo_td4320_6p4_gmp_lut_table_high4bit[0][0][0];
            pinfo->gmp_lut_table_len = ARRAY_3_SIZE(pct_auo_td4320_6p4_gmp_lut_table_low32bit);
            pinfo->xcc_table = pct_auo_td4320_6p4_xcc_table;
            pinfo->xcc_table_len = ARRAY_SIZE(pct_auo_td4320_6p4_xcc_table);
        }
        break;
    case PCT_AUO_NT36672A_6P4_PANEL:
        if (pinfo->gamma_support == 1)
        {
            pinfo->gamma_lut_table_R = pct_auo_nt36672a_6p4_gamma_lut_table_R;
            pinfo->gamma_lut_table_G = pct_auo_nt36672a_6p4_gamma_lut_table_G;
            pinfo->gamma_lut_table_B = pct_auo_nt36672a_6p4_gamma_lut_table_B;
            pinfo->gamma_lut_table_len = ARRAY_SIZE(pct_auo_nt36672a_6p4_gamma_lut_table_R);
            pinfo->igm_lut_table_R = pct_auo_nt36672a_6p4_igm_lut_table_R;
            pinfo->igm_lut_table_G = pct_auo_nt36672a_6p4_igm_lut_table_G;
            pinfo->igm_lut_table_B = pct_auo_nt36672a_6p4_igm_lut_table_B;
            pinfo->igm_lut_table_len = ARRAY_SIZE(pct_auo_nt36672a_6p4_igm_lut_table_R);
            pinfo->gmp_lut_table_low32bit = &pct_auo_nt36672a_6p4_gmp_lut_table_low32bit[0][0][0];
            pinfo->gmp_lut_table_high4bit = &pct_auo_nt36672a_6p4_gmp_lut_table_high4bit[0][0][0];
            pinfo->gmp_lut_table_len = ARRAY_3_SIZE(pct_auo_nt36672a_6p4_gmp_lut_table_low32bit);
            pinfo->xcc_table = pct_auo_nt36672a_6p4_xcc_table;
            pinfo->xcc_table_len = ARRAY_SIZE(pct_auo_nt36672a_6p4_xcc_table);
        }
        break;
    case PCT_BOE_NT36672A_6P4_PANEL:
        if (pinfo->gamma_support == 1)
        {
            pinfo->gamma_lut_table_R = pct_boe_nt36672a_6p4_gamma_lut_table_R;
            pinfo->gamma_lut_table_G = pct_boe_nt36672a_6p4_gamma_lut_table_G;
            pinfo->gamma_lut_table_B = pct_boe_nt36672a_6p4_gamma_lut_table_B;
            pinfo->gamma_lut_table_len = ARRAY_SIZE(pct_boe_nt36672a_6p4_gamma_lut_table_R);
            pinfo->igm_lut_table_R = pct_boe_nt36672a_6p4_igm_lut_table_R;
            pinfo->igm_lut_table_G = pct_boe_nt36672a_6p4_igm_lut_table_G;
            pinfo->igm_lut_table_B = pct_boe_nt36672a_6p4_igm_lut_table_B;
            pinfo->igm_lut_table_len = ARRAY_SIZE(pct_boe_nt36672a_6p4_igm_lut_table_R);
            pinfo->gmp_lut_table_low32bit = &pct_boe_nt36672a_6p4_gmp_lut_table_low32bit[0][0][0];
            pinfo->gmp_lut_table_high4bit = &pct_boe_nt36672a_6p4_gmp_lut_table_high4bit[0][0][0];
            pinfo->gmp_lut_table_len = ARRAY_3_SIZE(pct_boe_nt36672a_6p4_gmp_lut_table_low32bit);
            pinfo->xcc_table = pct_boe_nt36672a_6p4_xcc_table;
            pinfo->xcc_table_len = ARRAY_SIZE(pct_boe_nt36672a_6p4_xcc_table);
        }
        break;
    case PCT_LG_TD4320_6P4_PANEL:
        if (pinfo->gamma_support == 1)
        {
            pinfo->gamma_lut_table_R = pct_lg_td4320_6p4_gamma_lut_table_R;
            pinfo->gamma_lut_table_G = pct_lg_td4320_6p4_gamma_lut_table_G;
            pinfo->gamma_lut_table_B = pct_lg_td4320_6p4_gamma_lut_table_B;
            pinfo->gamma_lut_table_len = ARRAY_SIZE(pct_lg_td4320_6p4_gamma_lut_table_R);
            pinfo->igm_lut_table_R = pct_lg_td4320_6p4_igm_lut_table_R;
            pinfo->igm_lut_table_G = pct_lg_td4320_6p4_igm_lut_table_G;
            pinfo->igm_lut_table_B = pct_lg_td4320_6p4_igm_lut_table_B;
            pinfo->igm_lut_table_len = ARRAY_SIZE(pct_lg_td4320_6p4_igm_lut_table_R);
            pinfo->gmp_lut_table_low32bit = &pct_lg_td4320_6p4_gmp_lut_table_low32bit[0][0][0];
            pinfo->gmp_lut_table_high4bit = &pct_lg_td4320_6p4_gmp_lut_table_high4bit[0][0][0];
            pinfo->gmp_lut_table_len = ARRAY_3_SIZE(pct_lg_td4320_6p4_gmp_lut_table_low32bit);
            pinfo->xcc_table = pct_lg_td4320_6p4_xcc_table;
            pinfo->xcc_table_len = ARRAY_SIZE(pct_lg_td4320_6p4_xcc_table);
        }
        break;
    case PCT_TM_NT36672A_6P4_PANEL:
        if (pinfo->gamma_support == 1)
        {
            pinfo->gamma_lut_table_R = pct_tm_nt36672a_6p4_gamma_lut_table_R;
            pinfo->gamma_lut_table_G = pct_tm_nt36672a_6p4_gamma_lut_table_G;
            pinfo->gamma_lut_table_B = pct_tm_nt36672a_6p4_gamma_lut_table_B;
            pinfo->gamma_lut_table_len = ARRAY_SIZE(pct_tm_nt36672a_6p4_gamma_lut_table_R);
            pinfo->igm_lut_table_R = pct_tm_nt36672a_6p4_igm_lut_table_R;
            pinfo->igm_lut_table_G = pct_tm_nt36672a_6p4_igm_lut_table_G;
            pinfo->igm_lut_table_B = pct_tm_nt36672a_6p4_igm_lut_table_B;
            pinfo->igm_lut_table_len = ARRAY_SIZE(pct_tm_nt36672a_6p4_igm_lut_table_R);
            pinfo->gmp_lut_table_low32bit = &pct_tm_nt36672a_6p4_gmp_lut_table_low32bit[0][0][0];
            pinfo->gmp_lut_table_high4bit = &pct_tm_nt36672a_6p4_gmp_lut_table_high4bit[0][0][0];
            pinfo->gmp_lut_table_len = ARRAY_3_SIZE(pct_tm_nt36672a_6p4_gmp_lut_table_low32bit);
            pinfo->xcc_table = pct_tm_nt36672a_6p4_xcc_table;
            pinfo->xcc_table_len = ARRAY_SIZE(pct_tm_nt36672a_6p4_xcc_table);
        }
        break;
    case PCT_V4_CTC_NT36672A_6P4_PANEL:
        if (pinfo->gamma_support == 1)
        {
            pinfo->gamma_lut_table_R = pct_v4_ctc_nt36672a_6p4_gamma_lut_table_R;
            pinfo->gamma_lut_table_G = pct_v4_ctc_nt36672a_6p4_gamma_lut_table_G;
            pinfo->gamma_lut_table_B = pct_v4_ctc_nt36672a_6p4_gamma_lut_table_B;
            pinfo->gamma_lut_table_len = ARRAY_SIZE(pct_v4_ctc_nt36672a_6p4_gamma_lut_table_R);
            pinfo->igm_lut_table_R = pct_v4_ctc_nt36672a_6p4_igm_lut_table_R;
            pinfo->igm_lut_table_G = pct_v4_ctc_nt36672a_6p4_igm_lut_table_G;
            pinfo->igm_lut_table_B = pct_v4_ctc_nt36672a_6p4_igm_lut_table_B;
            pinfo->igm_lut_table_len = ARRAY_SIZE(pct_v4_ctc_nt36672a_6p4_igm_lut_table_R);
            pinfo->gmp_lut_table_low32bit = &pct_v4_ctc_nt36672a_6p4_gmp_lut_table_low32bit[0][0][0];
            pinfo->gmp_lut_table_high4bit = &pct_v4_ctc_nt36672a_6p4_gmp_lut_table_high4bit[0][0][0];
            pinfo->gmp_lut_table_len = ARRAY_3_SIZE(pct_v4_ctc_nt36672a_6p4_gmp_lut_table_low32bit);
            pinfo->xcc_table = pct_v4_ctc_nt36672a_6p4_xcc_table;
            pinfo->xcc_table_len = ARRAY_SIZE(pct_v4_ctc_nt36672a_6p4_xcc_table);
        }
        break;
    case PCT_V4_BOE_TD4320_6P4_PANEL:
        if (pinfo->gamma_support == 1)
        {
            pinfo->gamma_lut_table_R = pct_v4_boe_td4320_6p4_gamma_lut_table_R;
            pinfo->gamma_lut_table_G = pct_v4_boe_td4320_6p4_gamma_lut_table_G;
            pinfo->gamma_lut_table_B = pct_v4_boe_td4320_6p4_gamma_lut_table_B;
            pinfo->gamma_lut_table_len = ARRAY_SIZE(pct_v4_boe_td4320_6p4_gamma_lut_table_R);
            pinfo->igm_lut_table_R = pct_v4_boe_td4320_6p4_igm_lut_table_R;
            pinfo->igm_lut_table_G = pct_v4_boe_td4320_6p4_igm_lut_table_G;
            pinfo->igm_lut_table_B = pct_v4_boe_td4320_6p4_igm_lut_table_B;
            pinfo->igm_lut_table_len = ARRAY_SIZE(pct_v4_boe_td4320_6p4_igm_lut_table_R);
            pinfo->gmp_lut_table_low32bit = &pct_v4_boe_td4320_6p4_gmp_lut_table_low32bit[0][0][0];
            pinfo->gmp_lut_table_high4bit = &pct_v4_boe_td4320_6p4_gmp_lut_table_high4bit[0][0][0];
            pinfo->gmp_lut_table_len = ARRAY_3_SIZE(pct_v4_boe_td4320_6p4_gmp_lut_table_low32bit);
            pinfo->xcc_table = pct_v4_boe_td4320_6p4_xcc_table;
            pinfo->xcc_table_len = ARRAY_SIZE(pct_v4_boe_td4320_6p4_xcc_table);
        }
        break;
    case PCT_V4_AUO_TD4320_6P4_PANEL:
        if (pinfo->gamma_support == 1)
        {
            pinfo->gamma_lut_table_R = pct_v4_auo_td4320_6p4_gamma_lut_table_R;
            pinfo->gamma_lut_table_G = pct_v4_auo_td4320_6p4_gamma_lut_table_G;
            pinfo->gamma_lut_table_B = pct_v4_auo_td4320_6p4_gamma_lut_table_B;
            pinfo->gamma_lut_table_len = ARRAY_SIZE(pct_v4_auo_td4320_6p4_gamma_lut_table_R);
            pinfo->igm_lut_table_R = pct_v4_auo_td4320_6p4_igm_lut_table_R;
            pinfo->igm_lut_table_G = pct_v4_auo_td4320_6p4_igm_lut_table_G;
            pinfo->igm_lut_table_B = pct_v4_auo_td4320_6p4_igm_lut_table_B;
            pinfo->igm_lut_table_len = ARRAY_SIZE(pct_v4_auo_td4320_6p4_igm_lut_table_R);
            pinfo->gmp_lut_table_low32bit = &pct_v4_auo_td4320_6p4_gmp_lut_table_low32bit[0][0][0];
            pinfo->gmp_lut_table_high4bit = &pct_v4_auo_td4320_6p4_gmp_lut_table_high4bit[0][0][0];
            pinfo->gmp_lut_table_len = ARRAY_3_SIZE(pct_v4_auo_td4320_6p4_gmp_lut_table_low32bit);
            pinfo->xcc_table = pct_v4_auo_td4320_6p4_xcc_table;
            pinfo->xcc_table_len = ARRAY_SIZE(pct_v4_auo_td4320_6p4_xcc_table);
        }
        break;
    case PCT_V4_AUO_NT36672A_6P4_PANEL:
        if (pinfo->gamma_support == 1)
        {
            pinfo->gamma_lut_table_R = pct_v4_auo_nt36672a_6p4_gamma_lut_table_R;
            pinfo->gamma_lut_table_G = pct_v4_auo_nt36672a_6p4_gamma_lut_table_G;
            pinfo->gamma_lut_table_B = pct_v4_auo_nt36672a_6p4_gamma_lut_table_B;
            pinfo->gamma_lut_table_len = ARRAY_SIZE(pct_v4_auo_nt36672a_6p4_gamma_lut_table_R);
            pinfo->igm_lut_table_R = pct_v4_auo_nt36672a_6p4_igm_lut_table_R;
            pinfo->igm_lut_table_G = pct_v4_auo_nt36672a_6p4_igm_lut_table_G;
            pinfo->igm_lut_table_B = pct_v4_auo_nt36672a_6p4_igm_lut_table_B;
            pinfo->igm_lut_table_len = ARRAY_SIZE(pct_v4_auo_nt36672a_6p4_igm_lut_table_R);
            pinfo->gmp_lut_table_low32bit = &pct_v4_auo_nt36672a_6p4_gmp_lut_table_low32bit[0][0][0];
            pinfo->gmp_lut_table_high4bit = &pct_v4_auo_nt36672a_6p4_gmp_lut_table_high4bit[0][0][0];
            pinfo->gmp_lut_table_len = ARRAY_3_SIZE(pct_v4_auo_nt36672a_6p4_gmp_lut_table_low32bit);
            pinfo->xcc_table = pct_v4_auo_nt36672a_6p4_xcc_table;
            pinfo->xcc_table_len = ARRAY_SIZE(pct_v4_auo_nt36672a_6p4_xcc_table);
        }
        break;
    case PCT_V4_BOE_NT36672A_6P4_PANEL:
        if (pinfo->gamma_support == 1)
        {
            pinfo->gamma_lut_table_R = pct_v4_boe_nt36672a_6p4_gamma_lut_table_R;
            pinfo->gamma_lut_table_G = pct_v4_boe_nt36672a_6p4_gamma_lut_table_G;
            pinfo->gamma_lut_table_B = pct_v4_boe_nt36672a_6p4_gamma_lut_table_B;
            pinfo->gamma_lut_table_len = ARRAY_SIZE(pct_v4_boe_nt36672a_6p4_gamma_lut_table_R);
            pinfo->igm_lut_table_R = pct_v4_boe_nt36672a_6p4_igm_lut_table_R;
            pinfo->igm_lut_table_G = pct_v4_boe_nt36672a_6p4_igm_lut_table_G;
            pinfo->igm_lut_table_B = pct_v4_boe_nt36672a_6p4_igm_lut_table_B;
            pinfo->igm_lut_table_len = ARRAY_SIZE(pct_v4_boe_nt36672a_6p4_igm_lut_table_R);
            pinfo->gmp_lut_table_low32bit = &pct_v4_boe_nt36672a_6p4_gmp_lut_table_low32bit[0][0][0];
            pinfo->gmp_lut_table_high4bit = &pct_v4_boe_nt36672a_6p4_gmp_lut_table_high4bit[0][0][0];
            pinfo->gmp_lut_table_len = ARRAY_3_SIZE(pct_v4_boe_nt36672a_6p4_gmp_lut_table_low32bit);
            pinfo->xcc_table = pct_v4_boe_nt36672a_6p4_xcc_table;
            pinfo->xcc_table_len = ARRAY_SIZE(pct_v4_boe_nt36672a_6p4_xcc_table);
        }
        break;
    case PCT_V4_LG_TD4320_6P4_PANEL:
        if (pinfo->gamma_support == 1)
        {
            pinfo->gamma_lut_table_R = pct_v4_lg_td4320_6p4_gamma_lut_table_R;
            pinfo->gamma_lut_table_G = pct_v4_lg_td4320_6p4_gamma_lut_table_G;
            pinfo->gamma_lut_table_B = pct_v4_lg_td4320_6p4_gamma_lut_table_B;
            pinfo->gamma_lut_table_len = ARRAY_SIZE(pct_v4_lg_td4320_6p4_gamma_lut_table_R);
            pinfo->igm_lut_table_R = pct_v4_lg_td4320_6p4_igm_lut_table_R;
            pinfo->igm_lut_table_G = pct_v4_lg_td4320_6p4_igm_lut_table_G;
            pinfo->igm_lut_table_B = pct_v4_lg_td4320_6p4_igm_lut_table_B;
            pinfo->igm_lut_table_len = ARRAY_SIZE(pct_v4_lg_td4320_6p4_igm_lut_table_R);
            pinfo->gmp_lut_table_low32bit = &pct_v4_lg_td4320_6p4_gmp_lut_table_low32bit[0][0][0];
            pinfo->gmp_lut_table_high4bit = &pct_v4_lg_td4320_6p4_gmp_lut_table_high4bit[0][0][0];
            pinfo->gmp_lut_table_len = ARRAY_3_SIZE(pct_v4_lg_td4320_6p4_gmp_lut_table_low32bit);
            pinfo->xcc_table = pct_v4_lg_td4320_6p4_xcc_table;
            pinfo->xcc_table_len = ARRAY_SIZE(pct_v4_lg_td4320_6p4_xcc_table);
        }
        break;
    case PCT_V4_TM_NT36672A_6P4_PANEL:
        if (pinfo->gamma_support == 1)
        {
            pinfo->gamma_lut_table_R = pct_v4_tm_nt36672a_6p4_gamma_lut_table_R;
            pinfo->gamma_lut_table_G = pct_v4_tm_nt36672a_6p4_gamma_lut_table_G;
            pinfo->gamma_lut_table_B = pct_v4_tm_nt36672a_6p4_gamma_lut_table_B;
            pinfo->gamma_lut_table_len = ARRAY_SIZE(pct_v4_tm_nt36672a_6p4_gamma_lut_table_R);
            pinfo->igm_lut_table_R = pct_v4_tm_nt36672a_6p4_igm_lut_table_R;
            pinfo->igm_lut_table_G = pct_v4_tm_nt36672a_6p4_igm_lut_table_G;
            pinfo->igm_lut_table_B = pct_v4_tm_nt36672a_6p4_igm_lut_table_B;
            pinfo->igm_lut_table_len = ARRAY_SIZE(pct_v4_tm_nt36672a_6p4_igm_lut_table_R);
            pinfo->gmp_lut_table_low32bit = &pct_v4_tm_nt36672a_6p4_gmp_lut_table_low32bit[0][0][0];
            pinfo->gmp_lut_table_high4bit = &pct_v4_tm_nt36672a_6p4_gmp_lut_table_high4bit[0][0][0];
            pinfo->gmp_lut_table_len = ARRAY_3_SIZE(pct_v4_tm_nt36672a_6p4_gmp_lut_table_low32bit);
            pinfo->xcc_table = pct_v4_tm_nt36672a_6p4_xcc_table;
            pinfo->xcc_table_len = ARRAY_SIZE(pct_v4_tm_nt36672a_6p4_xcc_table);
        }
        break;
    case TAHITI_TUGL_BOE_NT37800F_TAH_PANEL:
        if (pinfo->gamma_support == 1)
        {
            pinfo->gamma_lut_table_R = tahiti_tugl_boe_nt37800f_tah_gamma_lut_table_R;
            pinfo->gamma_lut_table_G = tahiti_tugl_boe_nt37800f_tah_gamma_lut_table_G;
            pinfo->gamma_lut_table_B = tahiti_tugl_boe_nt37800f_tah_gamma_lut_table_B;
            pinfo->gamma_lut_table_len = ARRAY_SIZE(tahiti_tugl_boe_nt37800f_tah_gamma_lut_table_R);
            pinfo->igm_lut_table_R = tahiti_tugl_boe_nt37800f_tah_igm_lut_table_R;
            pinfo->igm_lut_table_G = tahiti_tugl_boe_nt37800f_tah_igm_lut_table_G;
            pinfo->igm_lut_table_B = tahiti_tugl_boe_nt37800f_tah_igm_lut_table_B;
            pinfo->igm_lut_table_len = ARRAY_SIZE(tahiti_tugl_boe_nt37800f_tah_igm_lut_table_R);
            pinfo->gmp_lut_table_low32bit = &tahiti_tugl_boe_nt37800f_tah_gmp_lut_table_low32bit[0][0][0];
            pinfo->gmp_lut_table_high4bit = &tahiti_tugl_boe_nt37800f_tah_gmp_lut_table_high4bit[0][0][0];
            pinfo->gmp_lut_table_len = ARRAY_3_SIZE(tahiti_tugl_boe_nt37800f_tah_gmp_lut_table_low32bit);
            pinfo->xcc_table = tahiti_tugl_boe_nt37800f_tah_xcc_table;
            pinfo->xcc_table_len = ARRAY_SIZE(tahiti_tugl_boe_nt37800f_tah_xcc_table);
        }
        break;
    case YAL_BOE_NT36672A_6P26_PANEL:
        if (pinfo->gamma_support == 1)
        {
            pinfo->gamma_lut_table_R = yal_boe_nt36672a_6p26_gamma_lut_table_R;
            pinfo->gamma_lut_table_G = yal_boe_nt36672a_6p26_gamma_lut_table_G;
            pinfo->gamma_lut_table_B = yal_boe_nt36672a_6p26_gamma_lut_table_B;
            pinfo->gamma_lut_table_len = ARRAY_SIZE(yal_boe_nt36672a_6p26_gamma_lut_table_R);
            pinfo->igm_lut_table_R = yal_boe_nt36672a_6p26_igm_lut_table_R;
            pinfo->igm_lut_table_G = yal_boe_nt36672a_6p26_igm_lut_table_G;
            pinfo->igm_lut_table_B = yal_boe_nt36672a_6p26_igm_lut_table_B;
            pinfo->igm_lut_table_len = ARRAY_SIZE(yal_boe_nt36672a_6p26_igm_lut_table_R);
            pinfo->gmp_lut_table_low32bit = &yal_boe_nt36672a_6p26_gmp_lut_table_low32bit[0][0][0];
            pinfo->gmp_lut_table_high4bit = &yal_boe_nt36672a_6p26_gmp_lut_table_high4bit[0][0][0];
            pinfo->gmp_lut_table_len = ARRAY_3_SIZE(yal_boe_nt36672a_6p26_gmp_lut_table_low32bit);
            pinfo->xcc_table = yal_boe_nt36672a_6p26_xcc_table;
            pinfo->xcc_table_len = ARRAY_SIZE(yal_boe_nt36672a_6p26_xcc_table);
        }
        break;
    case YAL_CTC_FT8719_6P26_PANEL:
        if (pinfo->gamma_support == 1)
        {
            pinfo->gamma_lut_table_R = yal_ctc_ft8719_6p26_gamma_lut_table_R;
            pinfo->gamma_lut_table_G = yal_ctc_ft8719_6p26_gamma_lut_table_G;
            pinfo->gamma_lut_table_B = yal_ctc_ft8719_6p26_gamma_lut_table_B;
            pinfo->gamma_lut_table_len = ARRAY_SIZE(yal_ctc_ft8719_6p26_gamma_lut_table_R);
            pinfo->igm_lut_table_R = yal_ctc_ft8719_6p26_igm_lut_table_R;
            pinfo->igm_lut_table_G = yal_ctc_ft8719_6p26_igm_lut_table_G;
            pinfo->igm_lut_table_B = yal_ctc_ft8719_6p26_igm_lut_table_B;
            pinfo->igm_lut_table_len = ARRAY_SIZE(yal_ctc_ft8719_6p26_igm_lut_table_R);
            pinfo->gmp_lut_table_low32bit = &yal_ctc_ft8719_6p26_gmp_lut_table_low32bit[0][0][0];
            pinfo->gmp_lut_table_high4bit = &yal_ctc_ft8719_6p26_gmp_lut_table_high4bit[0][0][0];
            pinfo->gmp_lut_table_len = ARRAY_3_SIZE(yal_ctc_ft8719_6p26_gmp_lut_table_low32bit);
            pinfo->xcc_table = yal_ctc_ft8719_6p26_xcc_table;
            pinfo->xcc_table_len = ARRAY_SIZE(yal_ctc_ft8719_6p26_xcc_table);
        }
        break;
    case YAL_CTC_NT36672A_6P26_PANEL:
        if (pinfo->gamma_support == 1)
        {
            pinfo->gamma_lut_table_R = yal_ctc_nt36672a_6p26_gamma_lut_table_R;
            pinfo->gamma_lut_table_G = yal_ctc_nt36672a_6p26_gamma_lut_table_G;
            pinfo->gamma_lut_table_B = yal_ctc_nt36672a_6p26_gamma_lut_table_B;
            pinfo->gamma_lut_table_len = ARRAY_SIZE(yal_ctc_nt36672a_6p26_gamma_lut_table_R);
            pinfo->igm_lut_table_R = yal_ctc_nt36672a_6p26_igm_lut_table_R;
            pinfo->igm_lut_table_G = yal_ctc_nt36672a_6p26_igm_lut_table_G;
            pinfo->igm_lut_table_B = yal_ctc_nt36672a_6p26_igm_lut_table_B;
            pinfo->igm_lut_table_len = ARRAY_SIZE(yal_ctc_nt36672a_6p26_igm_lut_table_R);
            pinfo->gmp_lut_table_low32bit = &yal_ctc_nt36672a_6p26_gmp_lut_table_low32bit[0][0][0];
            pinfo->gmp_lut_table_high4bit = &yal_ctc_nt36672a_6p26_gmp_lut_table_high4bit[0][0][0];
            pinfo->gmp_lut_table_len = ARRAY_3_SIZE(yal_ctc_nt36672a_6p26_gmp_lut_table_low32bit);
            pinfo->xcc_table = yal_ctc_nt36672a_6p26_xcc_table;
            pinfo->xcc_table_len = ARRAY_SIZE(yal_ctc_nt36672a_6p26_xcc_table);
        }
        break;
    case YAL_LG_TD4320_6P26_PANEL:
        if (pinfo->gamma_support == 1)
        {
            pinfo->gamma_lut_table_R = yal_lg_td4320_6p26_gamma_lut_table_R;
            pinfo->gamma_lut_table_G = yal_lg_td4320_6p26_gamma_lut_table_G;
            pinfo->gamma_lut_table_B = yal_lg_td4320_6p26_gamma_lut_table_B;
            pinfo->gamma_lut_table_len = ARRAY_SIZE(yal_lg_td4320_6p26_gamma_lut_table_R);
            pinfo->igm_lut_table_R = yal_lg_td4320_6p26_igm_lut_table_R;
            pinfo->igm_lut_table_G = yal_lg_td4320_6p26_igm_lut_table_G;
            pinfo->igm_lut_table_B = yal_lg_td4320_6p26_igm_lut_table_B;
            pinfo->igm_lut_table_len = ARRAY_SIZE(yal_lg_td4320_6p26_igm_lut_table_R);
            pinfo->gmp_lut_table_low32bit = &yal_lg_td4320_6p26_gmp_lut_table_low32bit[0][0][0];
            pinfo->gmp_lut_table_high4bit = &yal_lg_td4320_6p26_gmp_lut_table_high4bit[0][0][0];
            pinfo->gmp_lut_table_len = ARRAY_3_SIZE(yal_lg_td4320_6p26_gmp_lut_table_low32bit);
            pinfo->xcc_table = yal_lg_td4320_6p26_xcc_table;
            pinfo->xcc_table_len = ARRAY_SIZE(yal_lg_td4320_6p26_xcc_table);
        }
        break;
    case YAL_TM_NT36672A_6P26_PANEL:
        if (pinfo->gamma_support == 1)
        {
            pinfo->gamma_lut_table_R = yal_tm_nt36672a_6p26_gamma_lut_table_R;
            pinfo->gamma_lut_table_G = yal_tm_nt36672a_6p26_gamma_lut_table_G;
            pinfo->gamma_lut_table_B = yal_tm_nt36672a_6p26_gamma_lut_table_B;
            pinfo->gamma_lut_table_len = ARRAY_SIZE(yal_tm_nt36672a_6p26_gamma_lut_table_R);
            pinfo->igm_lut_table_R = yal_tm_nt36672a_6p26_igm_lut_table_R;
            pinfo->igm_lut_table_G = yal_tm_nt36672a_6p26_igm_lut_table_G;
            pinfo->igm_lut_table_B = yal_tm_nt36672a_6p26_igm_lut_table_B;
            pinfo->igm_lut_table_len = ARRAY_SIZE(yal_tm_nt36672a_6p26_igm_lut_table_R);
            pinfo->gmp_lut_table_low32bit = &yal_tm_nt36672a_6p26_gmp_lut_table_low32bit[0][0][0];
            pinfo->gmp_lut_table_high4bit = &yal_tm_nt36672a_6p26_gmp_lut_table_high4bit[0][0][0];
            pinfo->gmp_lut_table_len = ARRAY_3_SIZE(yal_tm_nt36672a_6p26_gmp_lut_table_low32bit);
            pinfo->xcc_table = yal_tm_nt36672a_6p26_xcc_table;
            pinfo->xcc_table_len = ARRAY_SIZE(yal_tm_nt36672a_6p26_xcc_table);
        }
        break;
    case YAL_TM_TD4320_6P26_PANEL:
        if (pinfo->gamma_support == 1)
        {
            pinfo->gamma_lut_table_R = yal_tm_td4320_6p26_gamma_lut_table_R;
            pinfo->gamma_lut_table_G = yal_tm_td4320_6p26_gamma_lut_table_G;
            pinfo->gamma_lut_table_B = yal_tm_td4320_6p26_gamma_lut_table_B;
            pinfo->gamma_lut_table_len = ARRAY_SIZE(yal_tm_td4320_6p26_gamma_lut_table_R);
            pinfo->igm_lut_table_R = yal_tm_td4320_6p26_igm_lut_table_R;
            pinfo->igm_lut_table_G = yal_tm_td4320_6p26_igm_lut_table_G;
            pinfo->igm_lut_table_B = yal_tm_td4320_6p26_igm_lut_table_B;
            pinfo->igm_lut_table_len = ARRAY_SIZE(yal_tm_td4320_6p26_igm_lut_table_R);
            pinfo->gmp_lut_table_low32bit = &yal_tm_td4320_6p26_gmp_lut_table_low32bit[0][0][0];
            pinfo->gmp_lut_table_high4bit = &yal_tm_td4320_6p26_gmp_lut_table_high4bit[0][0][0];
            pinfo->gmp_lut_table_len = ARRAY_3_SIZE(yal_tm_td4320_6p26_gmp_lut_table_low32bit);
            pinfo->xcc_table = yal_tm_td4320_6p26_xcc_table;
            pinfo->xcc_table_len = ARRAY_SIZE(yal_tm_td4320_6p26_xcc_table);
        }
        break;
    case YAL_TM_TD4330_6P26_PANEL:
        if (pinfo->gamma_support == 1)
        {
            pinfo->gamma_lut_table_R = yal_tm_td4330_6p26_gamma_lut_table_R;
            pinfo->gamma_lut_table_G = yal_tm_td4330_6p26_gamma_lut_table_G;
            pinfo->gamma_lut_table_B = yal_tm_td4330_6p26_gamma_lut_table_B;
            pinfo->gamma_lut_table_len = ARRAY_SIZE(yal_tm_td4330_6p26_gamma_lut_table_R);
            pinfo->igm_lut_table_R = yal_tm_td4330_6p26_igm_lut_table_R;
            pinfo->igm_lut_table_G = yal_tm_td4330_6p26_igm_lut_table_G;
            pinfo->igm_lut_table_B = yal_tm_td4330_6p26_igm_lut_table_B;
            pinfo->igm_lut_table_len = ARRAY_SIZE(yal_tm_td4330_6p26_igm_lut_table_R);
            pinfo->gmp_lut_table_low32bit = &yal_tm_td4330_6p26_gmp_lut_table_low32bit[0][0][0];
            pinfo->gmp_lut_table_high4bit = &yal_tm_td4330_6p26_gmp_lut_table_high4bit[0][0][0];
            pinfo->gmp_lut_table_len = ARRAY_3_SIZE(yal_tm_td4330_6p26_gmp_lut_table_low32bit);
            pinfo->xcc_table = yal_tm_td4330_6p26_xcc_table;
            pinfo->xcc_table_len = ARRAY_SIZE(yal_tm_td4330_6p26_xcc_table);
        }
        break;
    case YAL_V4_BOE_NT36672A_6P26_PANEL:
        if (pinfo->gamma_support == 1)
        {
            pinfo->gamma_lut_table_R = yal_v4_boe_nt36672a_6p26_gamma_lut_table_R;
            pinfo->gamma_lut_table_G = yal_v4_boe_nt36672a_6p26_gamma_lut_table_G;
            pinfo->gamma_lut_table_B = yal_v4_boe_nt36672a_6p26_gamma_lut_table_B;
            pinfo->gamma_lut_table_len = ARRAY_SIZE(yal_v4_boe_nt36672a_6p26_gamma_lut_table_R);
            pinfo->igm_lut_table_R = yal_v4_boe_nt36672a_6p26_igm_lut_table_R;
            pinfo->igm_lut_table_G = yal_v4_boe_nt36672a_6p26_igm_lut_table_G;
            pinfo->igm_lut_table_B = yal_v4_boe_nt36672a_6p26_igm_lut_table_B;
            pinfo->igm_lut_table_len = ARRAY_SIZE(yal_v4_boe_nt36672a_6p26_igm_lut_table_R);
            pinfo->gmp_lut_table_low32bit = &yal_v4_boe_nt36672a_6p26_gmp_lut_table_low32bit[0][0][0];
            pinfo->gmp_lut_table_high4bit = &yal_v4_boe_nt36672a_6p26_gmp_lut_table_high4bit[0][0][0];
            pinfo->gmp_lut_table_len = ARRAY_3_SIZE(yal_v4_boe_nt36672a_6p26_gmp_lut_table_low32bit);
            pinfo->xcc_table = yal_v4_boe_nt36672a_6p26_xcc_table;
            pinfo->xcc_table_len = ARRAY_SIZE(yal_v4_boe_nt36672a_6p26_xcc_table);
        }
        break;
    case YAL_V4_CTC_FT8719_6P26_PANEL:
        if (pinfo->gamma_support == 1)
        {
            pinfo->gamma_lut_table_R = yal_v4_ctc_ft8719_6p26_gamma_lut_table_R;
            pinfo->gamma_lut_table_G = yal_v4_ctc_ft8719_6p26_gamma_lut_table_G;
            pinfo->gamma_lut_table_B = yal_v4_ctc_ft8719_6p26_gamma_lut_table_B;
            pinfo->gamma_lut_table_len = ARRAY_SIZE(yal_v4_ctc_ft8719_6p26_gamma_lut_table_R);
            pinfo->igm_lut_table_R = yal_v4_ctc_ft8719_6p26_igm_lut_table_R;
            pinfo->igm_lut_table_G = yal_v4_ctc_ft8719_6p26_igm_lut_table_G;
            pinfo->igm_lut_table_B = yal_v4_ctc_ft8719_6p26_igm_lut_table_B;
            pinfo->igm_lut_table_len = ARRAY_SIZE(yal_v4_ctc_ft8719_6p26_igm_lut_table_R);
            pinfo->gmp_lut_table_low32bit = &yal_v4_ctc_ft8719_6p26_gmp_lut_table_low32bit[0][0][0];
            pinfo->gmp_lut_table_high4bit = &yal_v4_ctc_ft8719_6p26_gmp_lut_table_high4bit[0][0][0];
            pinfo->gmp_lut_table_len = ARRAY_3_SIZE(yal_v4_ctc_ft8719_6p26_gmp_lut_table_low32bit);
            pinfo->xcc_table = yal_v4_ctc_ft8719_6p26_xcc_table;
            pinfo->xcc_table_len = ARRAY_SIZE(yal_v4_ctc_ft8719_6p26_xcc_table);
        }
        break;
    case YAL_V4_CTC_NT36672A_6P26_PANEL:
        if (pinfo->gamma_support == 1)
        {
            pinfo->gamma_lut_table_R = yal_v4_ctc_nt36672a_6p26_gamma_lut_table_R;
            pinfo->gamma_lut_table_G = yal_v4_ctc_nt36672a_6p26_gamma_lut_table_G;
            pinfo->gamma_lut_table_B = yal_v4_ctc_nt36672a_6p26_gamma_lut_table_B;
            pinfo->gamma_lut_table_len = ARRAY_SIZE(yal_v4_ctc_nt36672a_6p26_gamma_lut_table_R);
            pinfo->igm_lut_table_R = yal_v4_ctc_nt36672a_6p26_igm_lut_table_R;
            pinfo->igm_lut_table_G = yal_v4_ctc_nt36672a_6p26_igm_lut_table_G;
            pinfo->igm_lut_table_B = yal_v4_ctc_nt36672a_6p26_igm_lut_table_B;
            pinfo->igm_lut_table_len = ARRAY_SIZE(yal_v4_ctc_nt36672a_6p26_igm_lut_table_R);
            pinfo->gmp_lut_table_low32bit = &yal_v4_ctc_nt36672a_6p26_gmp_lut_table_low32bit[0][0][0];
            pinfo->gmp_lut_table_high4bit = &yal_v4_ctc_nt36672a_6p26_gmp_lut_table_high4bit[0][0][0];
            pinfo->gmp_lut_table_len = ARRAY_3_SIZE(yal_v4_ctc_nt36672a_6p26_gmp_lut_table_low32bit);
            pinfo->xcc_table = yal_v4_ctc_nt36672a_6p26_xcc_table;
            pinfo->xcc_table_len = ARRAY_SIZE(yal_v4_ctc_nt36672a_6p26_xcc_table);
        }
        break;
    case YAL_V4_LG_TD4320_6P26_PANEL:
        if (pinfo->gamma_support == 1)
        {
            pinfo->gamma_lut_table_R = yal_v4_lg_td4320_6p26_gamma_lut_table_R;
            pinfo->gamma_lut_table_G = yal_v4_lg_td4320_6p26_gamma_lut_table_G;
            pinfo->gamma_lut_table_B = yal_v4_lg_td4320_6p26_gamma_lut_table_B;
            pinfo->gamma_lut_table_len = ARRAY_SIZE(yal_v4_lg_td4320_6p26_gamma_lut_table_R);
            pinfo->igm_lut_table_R = yal_v4_lg_td4320_6p26_igm_lut_table_R;
            pinfo->igm_lut_table_G = yal_v4_lg_td4320_6p26_igm_lut_table_G;
            pinfo->igm_lut_table_B = yal_v4_lg_td4320_6p26_igm_lut_table_B;
            pinfo->igm_lut_table_len = ARRAY_SIZE(yal_v4_lg_td4320_6p26_igm_lut_table_R);
            pinfo->gmp_lut_table_low32bit = &yal_v4_lg_td4320_6p26_gmp_lut_table_low32bit[0][0][0];
            pinfo->gmp_lut_table_high4bit = &yal_v4_lg_td4320_6p26_gmp_lut_table_high4bit[0][0][0];
            pinfo->gmp_lut_table_len = ARRAY_3_SIZE(yal_v4_lg_td4320_6p26_gmp_lut_table_low32bit);
            pinfo->xcc_table = yal_v4_lg_td4320_6p26_xcc_table;
            pinfo->xcc_table_len = ARRAY_SIZE(yal_v4_lg_td4320_6p26_xcc_table);
        }
        break;
    case YAL_V4_TM_NT36672A_6P26_PANEL:
        if (pinfo->gamma_support == 1)
        {
            pinfo->gamma_lut_table_R = yal_v4_tm_nt36672a_6p26_gamma_lut_table_R;
            pinfo->gamma_lut_table_G = yal_v4_tm_nt36672a_6p26_gamma_lut_table_G;
            pinfo->gamma_lut_table_B = yal_v4_tm_nt36672a_6p26_gamma_lut_table_B;
            pinfo->gamma_lut_table_len = ARRAY_SIZE(yal_v4_tm_nt36672a_6p26_gamma_lut_table_R);
            pinfo->igm_lut_table_R = yal_v4_tm_nt36672a_6p26_igm_lut_table_R;
            pinfo->igm_lut_table_G = yal_v4_tm_nt36672a_6p26_igm_lut_table_G;
            pinfo->igm_lut_table_B = yal_v4_tm_nt36672a_6p26_igm_lut_table_B;
            pinfo->igm_lut_table_len = ARRAY_SIZE(yal_v4_tm_nt36672a_6p26_igm_lut_table_R);
            pinfo->gmp_lut_table_low32bit = &yal_v4_tm_nt36672a_6p26_gmp_lut_table_low32bit[0][0][0];
            pinfo->gmp_lut_table_high4bit = &yal_v4_tm_nt36672a_6p26_gmp_lut_table_high4bit[0][0][0];
            pinfo->gmp_lut_table_len = ARRAY_3_SIZE(yal_v4_tm_nt36672a_6p26_gmp_lut_table_low32bit);
            pinfo->xcc_table = yal_v4_tm_nt36672a_6p26_xcc_table;
            pinfo->xcc_table_len = ARRAY_SIZE(yal_v4_tm_nt36672a_6p26_xcc_table);
        }
        break;
    case YAL_V4_TM_TD4320_6P26_PANEL:
        if (pinfo->gamma_support == 1)
        {
            pinfo->gamma_lut_table_R = yal_v4_tm_td4320_6p26_gamma_lut_table_R;
            pinfo->gamma_lut_table_G = yal_v4_tm_td4320_6p26_gamma_lut_table_G;
            pinfo->gamma_lut_table_B = yal_v4_tm_td4320_6p26_gamma_lut_table_B;
            pinfo->gamma_lut_table_len = ARRAY_SIZE(yal_v4_tm_td4320_6p26_gamma_lut_table_R);
            pinfo->igm_lut_table_R = yal_v4_tm_td4320_6p26_igm_lut_table_R;
            pinfo->igm_lut_table_G = yal_v4_tm_td4320_6p26_igm_lut_table_G;
            pinfo->igm_lut_table_B = yal_v4_tm_td4320_6p26_igm_lut_table_B;
            pinfo->igm_lut_table_len = ARRAY_SIZE(yal_v4_tm_td4320_6p26_igm_lut_table_R);
            pinfo->gmp_lut_table_low32bit = &yal_v4_tm_td4320_6p26_gmp_lut_table_low32bit[0][0][0];
            pinfo->gmp_lut_table_high4bit = &yal_v4_tm_td4320_6p26_gmp_lut_table_high4bit[0][0][0];
            pinfo->gmp_lut_table_len = ARRAY_3_SIZE(yal_v4_tm_td4320_6p26_gmp_lut_table_low32bit);
            pinfo->xcc_table = yal_v4_tm_td4320_6p26_xcc_table;
            pinfo->xcc_table_len = ARRAY_SIZE(yal_v4_tm_td4320_6p26_xcc_table);
        }
        break;
    case YAL_V4_TM_TD4330_6P26_PANEL:
        if (pinfo->gamma_support == 1)
        {
            pinfo->gamma_lut_table_R = yal_v4_tm_td4330_6p26_gamma_lut_table_R;
            pinfo->gamma_lut_table_G = yal_v4_tm_td4330_6p26_gamma_lut_table_G;
            pinfo->gamma_lut_table_B = yal_v4_tm_td4330_6p26_gamma_lut_table_B;
            pinfo->gamma_lut_table_len = ARRAY_SIZE(yal_v4_tm_td4330_6p26_gamma_lut_table_R);
            pinfo->igm_lut_table_R = yal_v4_tm_td4330_6p26_igm_lut_table_R;
            pinfo->igm_lut_table_G = yal_v4_tm_td4330_6p26_igm_lut_table_G;
            pinfo->igm_lut_table_B = yal_v4_tm_td4330_6p26_igm_lut_table_B;
            pinfo->igm_lut_table_len = ARRAY_SIZE(yal_v4_tm_td4330_6p26_igm_lut_table_R);
            pinfo->gmp_lut_table_low32bit = &yal_v4_tm_td4330_6p26_gmp_lut_table_low32bit[0][0][0];
            pinfo->gmp_lut_table_high4bit = &yal_v4_tm_td4330_6p26_gmp_lut_table_high4bit[0][0][0];
            pinfo->gmp_lut_table_len = ARRAY_3_SIZE(yal_v4_tm_td4330_6p26_gmp_lut_table_low32bit);
            pinfo->xcc_table = yal_v4_tm_td4330_6p26_xcc_table;
            pinfo->xcc_table_len = ARRAY_SIZE(yal_v4_tm_td4330_6p26_xcc_table);
        }
        break;
    default:
        LCD_KIT_INFO("Panel ID not detected %d\n", panel_id);
        break;
    }
}

static uint8_t lcd_kit_get_panel_id(uint32_t product_id, char* compatible)
{
    uint8_t lcd_panel_id = DEFAULT_AUO_OTM1901A_5P2_1080P_VIDEO_DEFAULT_PANEL;
    int i = 0;
    int len = strlen(compatible);
    int length = 0;
    for (i = 0; i < ARRAY_SIZE(lcd_kit_map); ++i) {
        length = strlen(lcd_kit_map[i].panel_compatible);
        if ((lcd_kit_map[i].product_id == product_id) && !strncmp(lcd_kit_map[i].panel_compatible, compatible, (length > len?length:len))){
            lcd_panel_id = lcd_kit_map[i].lcd_id;
            break;
        }
    }

    HISI_FB_INFO("lcd_panel_id = %d\n", lcd_panel_id);
    return lcd_panel_id;
}


#endif /*_LCDKIT_EFFECT__H_*/
